# Nome do Workflow que aparecerá na aba "Actions" do seu GitHub
name: Newman run

# Definição dos gatilhos (eventos) que disparam o pipeline
on:
  push:
    # O pipeline será executado automaticamente sempre que houver um 'git push' na branch main
    branches: [ "main" ]
  
# Bloco onde definimos os trabalhos (jobs) que a esteira vai executar
jobs:
  # Nome do nosso job (pode ser qualquer nome, aqui escolhemos 'newman')
  newman:
    # Sistema operacional da máquina virtual que o GitHub vai ligar na nuvem para rodar os testes
    runs-on: ubuntu-latest

    # Lista de passos (steps) que serão executados em sequência dentro da máquina virtual
    steps:
    # Passo 1: Faz o clone do seu repositório
    - uses: actions/checkout@v4
    
    # Passo 2: SELEÇÃO MANUAL DO NODE (A Solução!)
    # Este passo força a máquina virtual a usar a versão estável mais recente do Node 24
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'

    # Passo 3: Cria a pasta do relatório
    - name: Create directory for report
      run: |
        mkdir testArtifacts

    # Passo 4: Instala o Newman (agora usando o Node 24 que você setou acima!)
    - name: Install Newman
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    # Passo 5: Executa os testes
    - name: Run Test
      run: |
        newman run ServeRest_collection.json -r cli,htmlextra

    # Passo 6: Salva o relatório
    - name: Report
      uses: actions/upload-artifact@v4
      with:
        name: Report
        path: newman























      
    
